links:
# i3
- { src: ~/.dotfiles/i3, dest: ~/.config/i3 }
# i3blocks
- { src: ~/.dotfiles/i3blocks, dest: ~/.config/i3blocks }
# lxterminal
- { src: ~/.dotfiles/lxterminal, dest: ~/.config/lxterminal }
# SpaceVim
- { src: ~/.dotfiles/SpaceVim.d, dest: ~/.SpaceVim.d }
# zsh
- { src: ~/.dotfiles/zsh/.zshrc, dest: ~/.zshrc }
- { src: ~/.dotfiles/zsh/.p10k.zsh, dest: ~/.p10k.zsh }
